In [3]:
import numpy as np

In [6]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [12]:
np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [25]:
b =np.array([(1,2,3),(3,4,5)], dtype = float)
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


In [21]:
c = np.array([(1,2,3),(3,4,5)]) 
print(b)

[[1 2 3]
 [3 4 5]]


In [4]:
d = np.ones((2,3,4))
print(d)
d.ndim

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


3

In [5]:
d.shape

(2, 3, 4)

In [21]:
a1 = np.array({'1','20',"bhuvan",1.2,1.0,-1})
print(a1)

{1.2, 1.0, '1', 'bhuvan', '20', -1}


In [27]:
a2 = np.array([11,2,3,4,4,4])
print(a2)


[11  2  3  4  4  4]
